name: "Check conda for release candidates"
description: |
  Identify whether a recent release candidate has been published on conda.
inputs:
  channel:
    description: Channel where the package is found.
    required: true
    default: 'conda-forge'
  package:
    description: Package name
    required: true
  ndays:
    description: Max number of days to search for release candidates.
    required: true
    default: 7
  labels:
    description: Space-separated list of conda labels where RCs are found.
    required: true
    default: main
outputs:
    has_rc:
      description: Whether there is a release candidate for this package.
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.channel }}
    - ${{ inputs.package }}
    - ${{ inputs.ndays }}
    - ${{ inputs.labels }}
