on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  schedule:
    - cron: "0 0 * * 0"

defaults:
  run:
    shell: bash -l {0}

jobs:
  check-rc:
    runs-on: ubuntu-latest
    name: "Check for an OpenMM RC"
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: check
        with:
          channel: conda-forge
          package: openmm
          ndays: 30
          tags: 'main openmm_rc'
      - run: echo ${{ steps.check.outputs.hasrc }}
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Triggered Workflow
          token: ${{ secrets.DISPATCH_TOKEN }}
        if: ${{ steps.check.outputs.hasrc == 'True' }}
